// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/blog-designs/Magazine.tsx": () => import("../components/mockups/blog-designs/Magazine.tsx"),
  "./components/mockups/blog-designs/Minimal.tsx": () => import("../components/mockups/blog-designs/Minimal.tsx"),
  "./components/mockups/blog-designs/WarmJapanese.tsx": () => import("../components/mockups/blog-designs/WarmJapanese.tsx")
};
